### ISSUE TITLE
Docker image: onegambler/dropbox-syncer not working on Debian/CentOS hosts

### ISSUE THREAD

**Issue by zeduperes** [onegambler/docker-images#2]
I tried to use the docker image: onegambler/dropbox-syncer on hosts like Debian/CentOS and didn't work. When tried to start the container I got the error:
"standard_init_linux.go:211: exec user process caused "exec format error" 
Using the docker image on the raspberry it worked perfectly.

**Comment by zeduperes** [comment]
> I tried to use the docker image: onegambler/dropbox-syncer on hosts like Debian/CentOS and didn't work. When tried to start the container I got the error:
> "standard_init_linux.go:211: exec user process caused "exec format error"
> Using the docker image on the raspberry it worked perfectly.

I ran the command: docker run mplatform/mquery onegambler/dropbox-syncer
And I found that:
Image: onegambler/dropbox-syncer
 * Manifest List: No
 * Supports: arm/linux

Is it possible to make the image supports linux/amd64 ?

**Comment by onegambler** [comment]
Hi Jose, 
Yes, you're right, that images only works with arm architectures (raspberry pi). I do have another version in this repo `Dockerfile`, which use a x86 alpine base image but I never published to docker hub. If you need a amd64 version, you can simply checkout this repo and change that to point to a amd64 alpine base image ```docker pull amd64/alpine:latest``` and build from there.
